### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Mimickal/ReactionRoleBot#1]
I have the error [Error: insert into `reacts` (`emoji_id`, `guild_id`, `message_id`, `role_id`) values ('685131850762682463', '676117230349713458', '724212682630234122', '689816959730057237') - SQLITE_ERROR: no such table: reacts] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
What I have to do?

**Comment by Mimickal** [comment]
Looks like you need to run the knex migrations to set up the database. `npm run knex migrate:latest` should do it.
