### ISSUE TITLE
Can't get the bot to start

### ISSUE THREAD

**Issue by Relism** [Mimickal/ReactionRoleBot#14]
After setting up everything including the token thing, i get this issue.

![image](https://user-images.githubusercontent.com/83401018/129611295-190aef62-07b0-47f8-b86e-f848c1a63eec.png)

**Comment by Mimickal** [comment]
Are you running an older version of Node.js? That error is coming from within the Discord.js framework itself (the thing the bot is built on). Discord.js recommends Node version 16.6.0 or higher.
