### ISSUE TITLE
Have the bot create it's own message?

### ISSUE THREAD

**Issue by Xruptor** [Mimickal/ReactionRoleBot#21]
Instead of editing a users message.  Is there any command or way to make the bot create a message instead in a channel with description and title?  Use that as the message link to create roles?  Lets say the person whom's message is linked leaves the server.  That becomes problematic as we cannot edit their message.  But if it's the bots own message we can do it.

**Comment by Mimickal** [comment]
There is not currently a way to do this.

It's a decent idea, but I'm hesitant to add message content reading functions to the bot when Discord is planning on making that a special intent I will need to apply for. An alternative (and probably easier) thing might be to add a "migrate" or "copy" function that can reproduce all the role mappings from one message to another. Would that work for your needs?

**Comment by Xruptor** [comment]
Oh I figured it would be easy to do since a few of the bots already do something like that for reactions.  
Like @bot send-msg #channel title;;description

No worries then!

That would work great 😄 So someone could just make a new message.  Copy all the reactions over, then delete the original message.

**Comment by Mimickal** [comment]
The clone command is now live in master. Check out `/copy`!
