### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by Mimickal** [Mimickal/ReactionRoleBot#25]
Slash commands are currently in development. I will update this issue with more info as things get done.

**Comment by Mimickal** [comment]
All existing commands have been ported to slash commands in the https://github.com/Mimickal/ReactionRoleBot/tree/develop branch (along with some other fixes). I want to make a few more fixes and improvements, then I'll do an official 2.0 release with slash commands.

**Comment by Mimickal** [comment]
This took a little longer than I wanted. Doing some finishing testing on slash commands, then I'll write a migration guide for the new version and publish a release for slash commands.

**Comment by Mimickal** [comment]
Deploying to production was a wee bit of a nightmare, but slash commands are merged into master and should be live on my instance now.

**Comment by TBG-FR** [comment]
Glad you did it, good job !
