### ISSUE TITLE
Error while trying to add a reaction to a message

### ISSUE THREAD

**Issue by FC5570** [Mimickal/ReactionRoleBot#3]
Hey, I tried adding a reaction to a message, I made sure to select the message before that. While trying to add a reaction with: _**@bot role-add 👍 @Member**_, I get this error: **[Error: insert into `reacts` (`emoji_id`, `guild_id`, `message_id`, `role_id`) values ('�', '746419337509994509', '746744995813523557', '746741321070411868') - SQLITE_ERROR: no such table: reacts] {
  errno: 1,
  code: 'SQLITE_ERROR'**
Help please!

**Comment by Mimickal** [comment]
If you'd rather avoid the hassle of setting up your own instance, you can invite the instance I'm hosting with this link: https://discord.com/oauth2/authorize?client_id=692585944934514738&scope=bot&permissions=335881280

If you do want to host your own, you're having the same problem as #1. You've just got to run the knex migrations to set up your local database. This command should do it:
`npm run knex migrate:latest`

**Comment by FC5570** [comment]
I tried doing that and it said this:
**'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactionrolebot@1.1.1 knex: `node_modules/knex/bin/cli.js "migrate:latest"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactionrolebot@1.1.1 knex script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.**
Do you know whats causing this?

**Comment by Mimickal** [comment]
That sounds like you just need to run `npm install` inside the bot's root directory to download all the dependencies

**Comment by FC5570** [comment]
Alright, thanks for your help and sorry for not replying back, you can close this issue now. Have a great time.
