### ISSUE TITLE
Multiple (2) roles per reaction?

### ISSUE THREAD

**Issue by just-rich** [Mimickal/ReactionRoleBot#51]
Is it possible to set 2 roles per reaction?

There **might** be a slight issue with this. When the user unreacts to get the role removed, the bot doesn't know better to leave the base role assigned unless users has unreacted to all reactions.

**Comment by Mimickal** [comment]
You cannot currently map more than one role to an emoji. It's a design oversight rather than an intentional thing. I am currently working on a fix for that, which will come out soon along with slash commands.

Keep an eye on the develop branch.

**Comment by Mimickal** [comment]
This should now be possible as of v2.0.0
