### ISSUE TITLE
Help start bot

### ISSUE THREAD

**Issue by Tetsunokishi** [Mimickal/ReactionRoleBot#6]
Plase halp to start bot
![image](https://user-images.githubusercontent.com/72111329/102141058-4a144100-3e71-11eb-9c54-a0c90a9386d5.png)

**Comment by Mimickal** [comment]
The bot is trying to load a bot account token from a file that isn't present. You need to create a file that contains the token (just the token, in plain text. Nothing else).

By default, the bot tries to load it from the file named in that error message (`/etc/discord/ReactionRoleBot/token`). Since you're on Windows, that path might not work right. You can use a different token by adding a file path to the command (example: `node main.js path/to/my/token/file`).

If you'd rather not mess around with setting up your own instance of the bot, you can use my instance from this page https://top.gg/bot/692585944934514738

**Comment by Tetsunokishi** [comment]
@Mimickal i do
![image](https://user-images.githubusercontent.com/72111329/102147200-6c12c100-3e7b-11eb-8eae-8b285c95f951.png)

**Comment by Mimickal** [comment]
Use the command `node main.js token` to load that file

**Comment by ENOT1KK** [comment]
@Mimickal 
![image](https://user-images.githubusercontent.com/72111329/102150378-79cb4500-3e81-11eb-8925-4d2e0d456ecc.png)

**Comment by Tetsunokishi** [comment]
@Mimickal error
![image](https://user-images.githubusercontent.com/72111329/102150689-3a512880-3e82-11eb-8512-13e8f8ac2295.png)

**Comment by Mimickal** [comment]
Oh, you need to set up your database. `npm run knex migrate:latest`

**Comment by Tetsunokishi** [comment]
@Mimickal 
![image](https://user-images.githubusercontent.com/72111329/102155285-53f76d80-3e8c-11eb-845f-34c2389cc15b.png)

**Comment by Mimickal** [comment]
You need to install the bot dependencies. Run `npm install`

**Comment by Tetsunokishi** [comment]
@Mimickal 
![image](https://user-images.githubusercontent.com/72111329/102160579-beada680-3e96-11eb-80fb-53a9e2b8a6de.png)

**Comment by Mimickal** [comment]
Have you gone back through the other steps?

**Comment by Tetsunokishi** [comment]
@Mimickal I'm completely done with 0 just now.

**Comment by Mimickal** [comment]
Sorry, I'm not sure what you mean by that

**Comment by Tetsunokishi** [comment]
@Mimickal "Have you gone back through the other steps?" - Yes.

**Comment by Mimickal** [comment]
Try deleting the database file (should be `dev.sqlite3` in the project root), and then run the database migration again `npm run knex migrate:latest`.

**Comment by Tetsunokishi** [comment]
@Mimickal Not help. Can you give us a clean generated table? dev.sqlite3

**Comment by Mimickal** [comment]
Try this. This should be compatible with current master (v1.1.1)
[dev.sqlite.zip](https://github.com/Mimickal/ReactionRoleBot/files/5693069/dev.sqlite.zip)

Question -- are you just trying to run the bot? If so, I am running one you can use. https://top.gg/bot/692585944934514738

**Comment by Tetsunokishi** [comment]
I'ts work, whanks ^_^

**Comment by Tetsunokishi** [comment]
@Mimickal error for launch debian 9
![image](https://user-images.githubusercontent.com/72111329/102376995-3d106280-3fd5-11eb-915c-eda9ac70ca2f.png)

**Comment by Mimickal** [comment]
Looks like you need to `npm install` on that remote server
